name: deploy-production

on:
  push:
    branches:
      - "main"
	  
jobs:
  production-deployment
    runs-on: ubuntu-latest
    steps:
      - name: Env
          id: prep
          run: |
#		     BRANCH=${GITHUB_REF##*/}
             ${{ ${GITHUB_REF##*/}=='main' && BRANCH='production' || BRANCH=${GITHUB_REF##*/} }} 

             echo "Environment: $BRANCH" 
			  
